---
title: "📚 Publications"
---

## Preprints
**Gil J. B. Henriques\***, Simon van Vliet\*, Michael Doebeli. [Multilevel selection favors fragmentation modes that maintain cooperative interactions in multispecies communities.](https://www.biorxiv.org/content/10.1101/2021.03.18.436065v1) In *BioRxiv*. (\*Equal contribution)

## 2021
**Gil J. B. Henriques**, Koichi Ito, Christoph Hauert, Michael Doebeli. [On the importance of evolving phenotype distributions on evolutionary diversification.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008733) In *PLOS Computational Biology* 17:2, e1008733

## 2020
**Gil J. B. Henriques**, Matthew M. Osmond. [Cooperation can promote rescue or lead to evolutionary suicide during environmental change.](henriques_cv/papers/henriques2020.pdf) In *Evolution* 74:7, 1255--1273

Andrés E. Quiñones, **Gil J. B. Henriques**, Ido Pen. [Queen‑worker conflict can drive the evolution of social plymorphism and split sex ratios in facultatively eusocial life cycles.](henriques_cv/papers/quinones2020.pdf) In *Evolution* 74:1, 15--28 <font size="2">([Digest](henriques_cv/papers/digests/digest_quinones2019.pdf))</font>

## 2019
**Gil J. B. Henriques**, Simon Burton, Yaroslav Ispolatov, Michael Doebeli. [Acculturation drives the evolution of intergroup conflict.](henriques_cv/papers/henriques2019.pdf) In *Proceedings of the National Academy of Sciences of the USA* 116:28, 14089--14097 <font size="2">([Press](https://scientificinquirer.com/2019/09/19/conversations-with-burt-simon-and-gil-henriques-reframing-intergroup-conflicts/), [more press](https://www.sciencedaily.com/releases/2019/07/190709091146.htm))</font>

## 2016
Eva J. P. Lievens, **Gil J. B. Henriques**, Yannis Michalakis, Thomas Lenormand. [Maladaptive sex ratio adjustment in the invasive brine shrimp *Artemia franciscana*.](henriques_cv/papers/lievens2016.pdf) In *Current Biology* 26:11, 1463--1467 <font size="2">([Digest](henriques_cv/papers/digests/digest_lievens2016.pdf))</font>
