---
name: Gil J. B.
surname: Henriques
position: "PhD candidiate • Evolutionary biologist"
address: "Biodiversity Research Centre • University of British Columbia, Vancouver • Unceded Musqueam territory"
phone: +1 604 352 0004
www: gilhenriques.github.io/
email: "henriques@zoology.ubc.ca"
#twitter: mariecurie
github: GilHenriques
orcid: 0000-0003-0040-3996
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
headcolor: 414141
aboutme: "I am interested in the interplay of evolution and ecology. My current research focuses on the evolution of social behaviours such as cooperation and conflict. Other research topics include sex allocation and biological diversification. I use a theoretical approach (with an emphasis on adaptive dynamics and individual-based simulations), occasionally in combination with empirical work."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(tibble)
library(googlesheets4)
library(naniar)
```

# Education
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Education") %>%
  replace_with_na_all(condition = ~.x == "NA") %>%
  detailed_entries(with = Degree, 
                   what = Institution, 
                   when = Year, 
                   where = Location, 
                   why = Details, .protect = FALSE)
```


# Other Research Experience 
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "OtherResearch") %>%
  mutate(Year = as.character(Year)) %>% 
  detailed_entries(when = Year, 
                   with = Position, 
                   what = Institution, 
                   where = Location, 
                   why = Details, .protect = FALSE)
```

# Teaching and Outreach
***Teaching experience***
  ```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "TeachingExperience") %>%
  mutate(Year = as.character(Year)) %>% 
  detailed_entries(when = Year, 
                   with = Title, 
                   what = Institution, 
                   where = Location, 
                   why = Details, .protect = FALSE)
```

***Teaching training***
  ```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "TeachingTraining") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year,  
                what = Description, .protect = FALSE)
```

\pagebreak

***Outreach and science communication***
  ```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Outreach") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year,  
                what = Description, .protect = FALSE)
```

# Employment other than Research \& Teaching
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Employment") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year,  
                what = Description, .protect = FALSE)
```

# Publications
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Publications") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year, 
                with = Journal, 
                what = Reference, .protect = FALSE)
```

# Conference talks and posters
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Conferences") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year, 
                with = Type, 
                what = Details, .protect = FALSE)
```

# Competitive (merit-based) fellowships, scholarships and awards
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Awards") %>%
  mutate(Year = as.character(Year)) %>% 
  brief_entries(when = Year, 
                with = Money, 
                what = Award, .protect = FALSE)
```

# Languages
```{r}
read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Languages") %>%
  brief_entries(when = Type, 
                what = Description, .protect = FALSE)
```

# Service
```{r}
  read_sheet("https://docs.google.com/spreadsheets/d/17Q6xe3vOgU-Tt27Dv9xYBss2BLTEDe5HPXOGbpkRSjI/edit#gid=0",
           sheet = "Service") %>%
  brief_entries(when = Year, 
                what = Description, .protect = FALSE)
```
